### ISSUE TITLE
Misplaced /health and /ready in oss.yml

### ISSUE THREAD

**Issue by vlastahajek** [influxdata/openapi#31]
When comparing `contracts/oss.yml` with `swagger.yml` from the InfluxDB repo, the major difference is that 
`/health` and `/ready` are placed under the `/api/v2/` URL in the `oss.yml`, whereas `swagger.yml` defines them with the `servers` property:
```yml
  /health:
    servers:
      - url: /
```
