### ISSUE TITLE
Inconsistent reference mapping for: `CheckDiscriminator`, `Threshold`, `NotificationRuleDiscriminator` and `NotificationEndpointDiscrimator`

### ISSUE THREAD

**Issue by bednar** [influxdata/openapi#33]
The following API has inconsistent reference mapping. The `$ref` is mapped into local schema, but the `discriminator` is mapped by remote reference:

- https://github.com/influxdata/openapi/blob/c32f0055dc0fd4ee4410e7f325ce5b2c1717c031/contracts/oss.yml#L11328
- https://github.com/influxdata/openapi/blob/c32f0055dc0fd4ee4410e7f325ce5b2c1717c031/contracts/oss.yml#L11465
- https://github.com/influxdata/openapi/blob/c32f0055dc0fd4ee4410e7f325ce5b2c1717c031/contracts/oss.yml#L11618
- https://github.com/influxdata/openapi/blob/c32f0055dc0fd4ee4410e7f325ce5b2c1717c031/contracts/oss.yml#L11894

The mapping should looks like:

```yaml
CheckDiscriminator:
  oneOf:
    - $ref: '../common.yml#/components/schemas/DeadmanCheck'
    - $ref: '../common.yml#/components/schemas/ThresholdCheck'
    - $ref: '../common.yml#/components/schemas/CustomCheck'
  discriminator:
    propertyName: type
    mapping:
      deadman: '../common.yml#/components/schemas/DeadmanCheck'
      threshold: '../common.yml#/components/schemas/ThresholdCheck.yml'
      custom: '../common.yml#/components/schemas/CustomCheck.yml'
```

or

```yaml
CheckDiscriminator:
  oneOf:
    - $ref: '#/components/schemas/DeadmanCheck'
    - $ref: '#/components/schemas/ThresholdCheck'
    - $ref: '#/components/schemas/CustomCheck'
  discriminator:
    propertyName: type
    mapping:
      deadman: '#/components/schemas/DeadmanCheck'
      threshold: '#/components/schemas/ThresholdCheck.yml'
      custom: '#/components/schemas/CustomCheck.yml'
```
