### ISSUE TITLE
OSS header errors don't agree with spec

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/openapi#355]
`src/common/paths/query_analyze.yml` contains

```yaml
    default:
      description: Internal server error
      headers:
        X-Influx-Error:
          description: A string that describes the problem.
          schema:
            type: string
        X-Influx-Reference:
          description: The numeric reference code for the error type.
          schema:
            type: integer
```

but I don't see either of those error headers returned by OSS; I only see `X-Platform-Error-Code`.

We need to compare this with Cloud and then fix the spec or document the differences.
For now, I've added it as an additional header:

```yaml
    default:
      description: Internal server error
      headers:
        X-Platform-Error-Code:
          description: The reason for the error.
          schema:
            type: string
            example: "internal error"
        X-Influx-Error:
          description: A string that describes the problem.
          schema:
            type: string
        X-Influx-Reference:
          description: The numeric reference code for the error type.
          schema:
            type: integer
```
