### ISSUE TITLE
schema/TelegramNotificationRuleBase - property channel listed as required is not defined 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/openapi#560]
The property `channel` listed as _required_ is not listed under property definitions. 

__TelegramNotificationRuleBase.yml__

```  
type: object
  required: [type, messageTemplate, channel]
  properties:
    type:
      description: The discriminator between other types of notification rules is "telegram".
      type: string
      enum: [telegram]
    messageTemplate:
      description: The message template as a flux interpolated string.
      type: string
    parseMode:
      description: Parse mode of the message text per https://core.telegram.org/bots/api#formatting-options. Defaults to "MarkdownV2".
      type: string
      enum:
        - MarkdownV2
        - HTML
        - Markdown
    disableWebPagePreview:
      description: Disables preview of web links in the sent messages when "true". Defaults to "false".
      type: boolean
```
BTW: if the connection and sending of a notification is handled by the NotificationEndpoint defined as `endpointID` in NotificationRuleBase.yml, is it necessary to have the connection defining properties defined in the rule? 

NOTE: In the flux documentation the `telegram.message` function signature includes a channel argument. 
https://docs.influxdata.com/flux/v0.x/stdlib/contrib/sranka/telegram/message/

   channel
   text
   token
   ?disableWebPagePreview
   ?parseMode
   ?silent
   ?url   

 Latest commit in openapi

```
commit ad64ba87e7dd666feb80bbb85d1757b3d290d6c3 (HEAD -> master, origin/master, origin/HEAD)
Author: wiedld <wiedld@users.noreply.github.com>
Date:   Thu Sep 22 10:01:37 2022 -0700
```

Testing in K8SIDPE - latest commit
```
commit d3c2922e6c43cc6d7708a1622d6d2d7b1943b769 (HEAD -> master, origin/master, origin/HEAD)
Author: influx-acs[bot] <107396960+influx-acs[bot]@users.noreply.github.com>
Date:   Tue Sep 27 01:45:24 2022 +0000
```
