### ISSUE TITLE
/dashboards - POST - able to create dashboard without name property in the request

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/openapi#619]
Looking at the schema `src/common/schemas/CreateDashboardRequest.yml` ... 

```
  properties:
    orgID:
      type: string
      description: The ID of the organization that owns the dashboard.
    name:
      type: string
      description: The user-facing name of the dashboard.
    description:
      type: string
      description: The user-facing description of the dashboard.
  required:
    - orgID
    - name
```
... I see that the name property is __required__.  

However when testing the `/dashboards` endpoint for `POST` against the latest influxdb implementation.  I am able to create a dashboard with the `name` property missing from the request.  

Is this definition up to date?  Or is this an issue in influxdb?  

Testing against K8S-IDPE remocal.  Latest commit.

```
commit 36edfae0f1409f79490e31e43846c9e258329e2c (HEAD -> master, origin/master, origin/HEAD)
Author: Cannon Palms <cpalms@influxdata.com>
Date:   Mon Nov 28 21:23:47 2022 -0500

```
