### ISSUE TITLE
/dashboards/{dashboardID}/cells PUT - property viewID in Cell schema seems to be ignored

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/openapi#622]
In the common schema `Cell` is a property `viewID`.  I've tried to set erroneous values to this property and send it as part of a requestBody, however it seems to be ignored by the server.  Does it still serve a purpose? Or since views are now handled by the `../cells/${cellID}/views` context, can it be removed?   

src/common/schemas/Cell.yml

```
  type: object
  properties:
    id:
      type: string
    links:
      type: object
      properties:
        self:
          type: string
        view:
          type: string
    x:
      type: integer
      format: int32
    "y": # Quoted to prevent YAML parser from interpreting y as shorthand for true.
      type: integer
      format: int32
    w:
      type: integer
      format: int32
    h:
      type: integer
      format: int32
    viewID:
      type: string
      description: The reference to a view from the views API.

```
